## Week 8
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
#yes there is difference list_ is normal list and array_list is numpy array
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [14]:
def printt(x):
    for i in x:
        print(f'data type of {i} is {type(i)}')
print("list_")
printt(list_)
print("array_list")
printt(array_list)


list_
data type of 1 is <class 'str'>
data type of 2 is <class 'str'>
data type of 3 is <class 'str'>
data type of 4 is <class 'str'>
data type of 5 is <class 'str'>
array_list
data type of 1 is <class 'numpy.int32'>
data type of 2 is <class 'numpy.int32'>
data type of 3 is <class 'numpy.int32'>
data type of 4 is <class 'numpy.int32'>
data type of 5 is <class 'numpy.int32'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [7]:
array_list = np.array(object = list_, dtype = int) #This line of code creates array_list which is an numpy array, to it objects of list_ is passed and it's datatype is set to int
print("list_")
printt(list_)
print("array_list")
printt(array_list)

list_
data type of 1 is <class 'str'>
data type of 2 is <class 'str'>
data type of 3 is <class 'str'>
data type of 4 is <class 'str'>
data type of 5 is <class 'str'>
array_list
data type of 1 is <class 'numpy.int32'>
data type of 2 is <class 'numpy.int32'>
data type of 3 is <class 'numpy.int32'>
data type of 4 is <class 'numpy.int32'>
data type of 5 is <class 'numpy.int32'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [24]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
def printt(x):
    print(x)
    print("shape is ",x.shape)
    print("size is ",x.size)

printt(num_array)

[[1 2 3]
 [4 5 6]]
shape is  (2, 3)
size is  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
arr=np.zeros((3,3))
print(arr)
print(arr.shape)
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [29]:
arr=np.eye(5,dtype=int)
print(arr.shape)
print(arr.size)
print(arr)

(5, 5)
25
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
